// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD7pVEmaLsqmSIOY9gzc5pxFQ_YeS0NaY',
    appId: '1:138876399906:web:c4365057d323151e3a357b',
    messagingSenderId: '138876399906',
    projectId: 'chatbot-app-708d8',
    authDomain: 'chatbot-app-708d8.firebaseapp.com',
    storageBucket: 'chatbot-app-708d8.firebasestorage.app',
    measurementId: 'G-KTE242FPSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfsvOecd7ZBgJdyhM0UU4unhw5ksvBdk8',
    appId: '1:138876399906:android:8f1b47c859c7210d3a357b',
    messagingSenderId: '138876399906',
    projectId: 'chatbot-app-708d8',
    storageBucket: 'chatbot-app-708d8.firebasestorage.app',
  );
}
